export const teamKeyMap: Record<string,string> = {
  'Arizona Diamondbacks':     'arizona-diamondbacks',
  'Atlanta Braves':           'atlanta-braves',
  'Baltimore Orioles':        'baltimore-orioles',
  'Boston Red Sox':           'boston-red-sox',
  'Chicago Cubs':             'chicago-cubs',
  'Chicago White Sox':        'chicago-white-sox',
  'Cincinnati Reds':          'cincinnati-reds',
  'Cleveland Guardians':      'cleveland-guardians',
  'Colorado Rockies':         'colorado-rockies',
  'Detroit Tigers':           'detroit-tigers',
  'Houston Astros':           'houston-astros',
  'Kansas City Royals':       'kansas-city-royals',
  'Los Angeles Angels':       'los-angeles-angels',
  'Los Angeles Dodgers':      'los-angeles-dodgers',
  'Miami Marlins':            'miami-marlins',
  'Milwaukee Brewers':        'milwaukee-brewers',
  'Minnesota Twins':          'minnesota-twins',
  'New York Mets':            'new-york-mets',
  'New York Yankees':         'new-york-yankees',
  'Oakland Athletics':        'oakland-athletics',
  'Philadelphia Phillies':    'philadelphia-phillies',
  'Pittsburgh Pirates':       'pittsburgh-pirates',
  'San Diego Padres':         'san-diego-padres',
  'San Francisco Giants':     'san-francisco-giants',
  'Seattle Mariners':         'seattle-mariners',
  'St. Louis Cardinals':      'st-louis-cardinals',
  'Tampa Bay Rays':           'tampa-bay-rays',
  'Texas Rangers':            'texas-rangers',
  'Toronto Blue Jays':        'toronto-blue-jays',
  'Washington Nationals':     'washington-nationals'
  // …add any historical or alternate names here
};