import { MlbBatting, MlbBattingFullName, MlbHistoricalTeamFullName, MlbLeagueDivision, MlbLeagueDivisionFullName, MlbTeam, MlbTeamFullName, MlbTeamKey, MlbThrowing, MlbThrowingFullName } from "../models/mlb.models";
import { CountryBornFullName, TeamFullName, TeamType } from "../models/bio-ball.models";
import { CountryBorn } from "../models/bio-ball.models";
import { NflTeamFullName } from "../models/nfl.models";
import { NflTeam } from "../models/nfl.models";

export const MlbTeamAbbreviationMap: { [key in MlbTeamFullName]: MlbTeam } = {
    [MlbTeamFullName.ARIZONA_DIAMONDBACKS]: MlbTeam.ARI,
    [MlbTeamFullName.ATLANTA_BRAVES]: MlbTeam.ATL,
    [MlbTeamFullName.BALTIMORE_ORIOLES]: MlbTeam.BAL,
    [MlbTeamFullName.BOSTON_RED_SOX]: MlbTeam.BOS,
    [MlbTeamFullName.CHICAGO_CUBS]: MlbTeam.CHC,
    [MlbTeamFullName.CHICAGO_WHITE_SOX]: MlbTeam.CHW,
    [MlbTeamFullName.CINCINNATI_REDS]: MlbTeam.CIN,
    [MlbTeamFullName.CLEVELAND_GUARDIANS]: MlbTeam.CLE,
    [MlbTeamFullName.COLORADO_ROCKIES]: MlbTeam.COL,
    [MlbTeamFullName.DETROIT_TIGERS]: MlbTeam.DET,
    [MlbTeamFullName.HOUSTON_ASTROS]: MlbTeam.HOU,
    [MlbTeamFullName.KANSAS_CITY_ROYALS]: MlbTeam.KCR,
    [MlbTeamFullName.LOS_ANGELES_ANGELS]: MlbTeam.LAA,
    [MlbTeamFullName.LOS_ANGELES_DODGERS]: MlbTeam.LAD,
    [MlbTeamFullName.MIAMI_MARLINS]: MlbTeam.MIA,
    [MlbTeamFullName.MILWAUKEE_BREWERS]: MlbTeam.MIL,
    [MlbTeamFullName.MINNESOTA_TWINS]: MlbTeam.MIN,
    [MlbTeamFullName.NEW_YORK_METS]: MlbTeam.NYM,
    [MlbTeamFullName.NEW_YORK_YANKEES]: MlbTeam.NYY,
    [MlbTeamFullName.OAKLAND_ATHLETICS]: MlbTeam.OAK,
    [MlbTeamFullName.PHILADELPHIA_PHILLIES]: MlbTeam.PHI,
    [MlbTeamFullName.PITTSBURGH_PIRATES]: MlbTeam.PIT,
    [MlbTeamFullName.SAN_DIEGO_PADRES]: MlbTeam.SDP,
    [MlbTeamFullName.SAN_FRANCISCO_GIANTS]: MlbTeam.SFG,
    [MlbTeamFullName.SEATTLE_MARINERS]: MlbTeam.SEA,
    [MlbTeamFullName.ST_LOUIS_CARDINALS]: MlbTeam.STL,
    [MlbTeamFullName.TAMPA_BAY_RAYS]: MlbTeam.TBR,
    [MlbTeamFullName.TEXAS_RANGERS]: MlbTeam.TEX,
    [MlbTeamFullName.TORONTO_BLUE_JAYS]: MlbTeam.TOR,
    [MlbTeamFullName.WASHINGTON_NATIONALS]: MlbTeam.WSN,
};

export const LeagueDivisionAbbreviationMap: { [key in MlbLeagueDivisionFullName]: MlbLeagueDivision } = {
    [MlbLeagueDivisionFullName.AL_EAST]: MlbLeagueDivision.AL_EAST,
    [MlbLeagueDivisionFullName.AL_WEST]: MlbLeagueDivision.AL_WEST,
    [MlbLeagueDivisionFullName.AL_CENTRAL]: MlbLeagueDivision.AL_CENTRAL,
    [MlbLeagueDivisionFullName.NL_EAST]: MlbLeagueDivision.NL_EAST,
    [MlbLeagueDivisionFullName.NL_WEST]: MlbLeagueDivision.NL_WEST,
    [MlbLeagueDivisionFullName.NL_CENTRAL]: MlbLeagueDivision.NL_CENTRAL,
};

export const BattingAbbreviationMap: { [key in MlbBattingFullName]: MlbBatting } = {
    [MlbBattingFullName.R]: MlbBatting.R,
    [MlbBattingFullName.L]: MlbBatting.L,
    [MlbBattingFullName.S]: MlbBatting.S,
};

export const ThrowingAbbreviationMap: { [key in MlbThrowingFullName]: MlbThrowing } = {
    [MlbThrowingFullName.R]: MlbThrowing.R,
    [MlbThrowingFullName.L]: MlbThrowing.L,
    [MlbThrowingFullName.B]: MlbThrowing.B,
};

export const CountryBornAbbreviationMap: { [key in CountryBornFullName]: CountryBorn } = {
    [CountryBornFullName.USA]: CountryBorn.USA,
    [CountryBornFullName.DR]: CountryBorn.DR,
    [CountryBornFullName.VEN]: CountryBorn.VEN,
    [CountryBornFullName.PR]: CountryBorn.PR,
    [CountryBornFullName.CUB]: CountryBorn.CUB,
    [CountryBornFullName.CAN]: CountryBorn.CAN,
    [CountryBornFullName.MEX]: CountryBorn.MEX,
    [CountryBornFullName.COL]: CountryBorn.COL,
    [CountryBornFullName.KOR]: CountryBorn.KOR,
    [CountryBornFullName.JPN]: CountryBorn.JPN,
    [CountryBornFullName.PAN]: CountryBorn.PAN,
    [CountryBornFullName.AUS]: CountryBorn.AUS,
    [CountryBornFullName.BRA]: CountryBorn.BRA,
    [CountryBornFullName.NIC]: CountryBorn.NIC,
    [CountryBornFullName.ARU]: CountryBorn.ARU,
    [CountryBornFullName.BAH]: CountryBorn.BAH,
    [CountryBornFullName.CUR]: CountryBorn.CUR,
    [CountryBornFullName.HON]: CountryBorn.HON,
    [CountryBornFullName.PER]: CountryBorn.PER,
    [CountryBornFullName.TWN]: CountryBorn.TWN,
    [CountryBornFullName.GER]: CountryBorn.GER,
    [CountryBornFullName.MEX_MEX]: CountryBorn.MEX,
    [CountryBornFullName.ROK]: CountryBorn.KOR,
    [CountryBornFullName.PCZ]: CountryBorn.PAN
}

export const MlbAbbreviationToFullNameMap: { [key in MlbTeam]: MlbTeamFullName } = {
  [MlbTeam.ARI]: MlbTeamFullName.ARIZONA_DIAMONDBACKS,
  [MlbTeam.ATL]: MlbTeamFullName.ATLANTA_BRAVES,
  [MlbTeam.BAL]: MlbTeamFullName.BALTIMORE_ORIOLES,
  [MlbTeam.BOS]: MlbTeamFullName.BOSTON_RED_SOX,
  [MlbTeam.CHC]: MlbTeamFullName.CHICAGO_CUBS,
  [MlbTeam.CHW]: MlbTeamFullName.CHICAGO_WHITE_SOX,
  [MlbTeam.CIN]: MlbTeamFullName.CINCINNATI_REDS,
  [MlbTeam.CLE]: MlbTeamFullName.CLEVELAND_GUARDIANS,
  [MlbTeam.COL]: MlbTeamFullName.COLORADO_ROCKIES,
  [MlbTeam.DET]: MlbTeamFullName.DETROIT_TIGERS,
  [MlbTeam.HOU]: MlbTeamFullName.HOUSTON_ASTROS,
  [MlbTeam.KCR]: MlbTeamFullName.KANSAS_CITY_ROYALS,
  [MlbTeam.LAA]: MlbTeamFullName.LOS_ANGELES_ANGELS,
  [MlbTeam.LAD]: MlbTeamFullName.LOS_ANGELES_DODGERS,
  [MlbTeam.MIA]: MlbTeamFullName.MIAMI_MARLINS,
  [MlbTeam.MIL]: MlbTeamFullName.MILWAUKEE_BREWERS,
  [MlbTeam.MIN]: MlbTeamFullName.MINNESOTA_TWINS,
  [MlbTeam.NYM]: MlbTeamFullName.NEW_YORK_METS,
  [MlbTeam.NYY]: MlbTeamFullName.NEW_YORK_YANKEES,
  [MlbTeam.OAK]: MlbTeamFullName.OAKLAND_ATHLETICS,
  [MlbTeam.PHI]: MlbTeamFullName.PHILADELPHIA_PHILLIES,
  [MlbTeam.PIT]: MlbTeamFullName.PITTSBURGH_PIRATES,
  [MlbTeam.SDP]: MlbTeamFullName.SAN_DIEGO_PADRES,
  [MlbTeam.SFG]: MlbTeamFullName.SAN_FRANCISCO_GIANTS,
  [MlbTeam.SEA]: MlbTeamFullName.SEATTLE_MARINERS,
  [MlbTeam.STL]: MlbTeamFullName.ST_LOUIS_CARDINALS,
  [MlbTeam.TBR]: MlbTeamFullName.TAMPA_BAY_RAYS,
  [MlbTeam.TEX]: MlbTeamFullName.TEXAS_RANGERS,
  [MlbTeam.TOR]: MlbTeamFullName.TORONTO_BLUE_JAYS,
  [MlbTeam.WSN]: MlbTeamFullName.WASHINGTON_NATIONALS,
};

export const MlbTeamKeyToFullNameMap: { [key in MlbTeamKey]: MlbTeamFullName | MlbHistoricalTeamFullName } = {
  [MlbTeamKey.ARIZONA_DIAMONDBACKS]: MlbTeamFullName.ARIZONA_DIAMONDBACKS,
  [MlbTeamKey.ATHLETICS]: MlbHistoricalTeamFullName.ATHLETICS,
  [MlbTeamKey.ATLANTA_BRAVES]: MlbTeamFullName.ATLANTA_BRAVES,
  [MlbTeamKey.BALTIMORE_ORIOLES]: MlbTeamFullName.BALTIMORE_ORIOLES,
  [MlbTeamKey.BOSTON_RED_SOX]: MlbTeamFullName.BOSTON_RED_SOX,
  [MlbTeamKey.CHICAGO_CUBS]: MlbTeamFullName.CHICAGO_CUBS,
  [MlbTeamKey.CHICAGO_WHITE_SOX]: MlbTeamFullName.CHICAGO_WHITE_SOX,
  [MlbTeamKey.CINCINNATI_REDS]: MlbTeamFullName.CINCINNATI_REDS,
  [MlbTeamKey.CLEVELAND_GUARDIANS]: MlbTeamFullName.CLEVELAND_GUARDIANS,
  [MlbTeamKey.COLORADO_ROCKIES]: MlbTeamFullName.COLORADO_ROCKIES,
  [MlbTeamKey.DETROIT_TIGERS]: MlbTeamFullName.DETROIT_TIGERS,
  [MlbTeamKey.HOUSTON_ASTROS]: MlbTeamFullName.HOUSTON_ASTROS,
  [MlbTeamKey.KANSAS_CITY_ROYALS]: MlbTeamFullName.KANSAS_CITY_ROYALS,
  [MlbTeamKey.LOS_ANGELES_ANGELS]: MlbTeamFullName.LOS_ANGELES_ANGELS,
  [MlbTeamKey.LOS_ANGELES_DODGERS]: MlbTeamFullName.LOS_ANGELES_DODGERS,
  [MlbTeamKey.MIAMI_MARLINS]: MlbTeamFullName.MIAMI_MARLINS,
  [MlbTeamKey.MILWAUKEE_BREWERS]: MlbTeamFullName.MILWAUKEE_BREWERS,
  [MlbTeamKey.MINNESOTA_TWINS]: MlbTeamFullName.MINNESOTA_TWINS,
  [MlbTeamKey.NEW_YORK_METS]: MlbTeamFullName.NEW_YORK_METS,
  [MlbTeamKey.NEW_YORK_YANKEES]: MlbTeamFullName.NEW_YORK_YANKEES,
  [MlbTeamKey.OAKLAND_ATHLETICS]: MlbTeamFullName.OAKLAND_ATHLETICS,
  [MlbTeamKey.PHILADELPHIA_PHILLIES]: MlbTeamFullName.PHILADELPHIA_PHILLIES,
  [MlbTeamKey.PITTSBURGH_PIRATES]: MlbTeamFullName.PITTSBURGH_PIRATES,
  [MlbTeamKey.SAN_DIEGO_PADRES]: MlbTeamFullName.SAN_DIEGO_PADRES,
  [MlbTeamKey.SAN_FRANCISCO_GIANTS]: MlbTeamFullName.SAN_FRANCISCO_GIANTS,
  [MlbTeamKey.SEATTLE_MARINERS]: MlbTeamFullName.SEATTLE_MARINERS,
  [MlbTeamKey.ST_LOUIS_CARDINALS]: MlbTeamFullName.ST_LOUIS_CARDINALS,
  [MlbTeamKey.TAMPA_BAY_RAYS]: MlbTeamFullName.TAMPA_BAY_RAYS,
  [MlbTeamKey.TEXAS_RANGERS]: MlbTeamFullName.TEXAS_RANGERS,
  [MlbTeamKey.TORONTO_BLUE_JAYS]: MlbTeamFullName.TORONTO_BLUE_JAYS,
  [MlbTeamKey.WASHINGTON_NATIONALS]: MlbTeamFullName.WASHINGTON_NATIONALS,
  [MlbTeamKey.CALIFORNIA_ANGELS]: MlbHistoricalTeamFullName.CALIFORNIA_ANGELS,
  [MlbTeamKey.ANAHEIM_ANGELS]: MlbHistoricalTeamFullName.ANAHEIM_ANGELS,
  [MlbTeamKey.LOS_ANGELES_ANGELS_OF_ANAHEIM]: MlbHistoricalTeamFullName.LOS_ANGELES_ANGELS_OF_ANAHEIM,
  [MlbTeamKey.CLEVELAND_INDIANS]: MlbHistoricalTeamFullName.CLEVELAND_INDIANS,
  [MlbTeamKey.FLORIDA_MARLINS]: MlbHistoricalTeamFullName.FLORIDA_MARLINS,
  [MlbTeamKey.MONTREAL_EXPOS]: MlbHistoricalTeamFullName.MONTREAL_EXPOS,
  [MlbTeamKey.TAMPA_BAY_DEVIL_RAYS]: MlbHistoricalTeamFullName.TAMPA_BAY_DEVIL_RAYS,
};

export const MlbTeamFullNameToKeyMap: { [key in MlbTeamFullName | MlbHistoricalTeamFullName]: MlbTeamKey } = {
  [MlbTeamFullName.ARIZONA_DIAMONDBACKS]: MlbTeamKey.ARIZONA_DIAMONDBACKS,
  [MlbTeamFullName.ATLANTA_BRAVES]: MlbTeamKey.ATLANTA_BRAVES,
  [MlbTeamFullName.BALTIMORE_ORIOLES]: MlbTeamKey.BALTIMORE_ORIOLES,
  [MlbTeamFullName.BOSTON_RED_SOX]: MlbTeamKey.BOSTON_RED_SOX,
  [MlbTeamFullName.CHICAGO_CUBS]: MlbTeamKey.CHICAGO_CUBS,
  [MlbTeamFullName.CHICAGO_WHITE_SOX]: MlbTeamKey.CHICAGO_WHITE_SOX,
  [MlbTeamFullName.CINCINNATI_REDS]: MlbTeamKey.CINCINNATI_REDS,
  [MlbTeamFullName.CLEVELAND_GUARDIANS]: MlbTeamKey.CLEVELAND_GUARDIANS,
  [MlbTeamFullName.COLORADO_ROCKIES]: MlbTeamKey.COLORADO_ROCKIES,
  [MlbTeamFullName.DETROIT_TIGERS]: MlbTeamKey.DETROIT_TIGERS,
  [MlbTeamFullName.HOUSTON_ASTROS]: MlbTeamKey.HOUSTON_ASTROS,
  [MlbTeamFullName.KANSAS_CITY_ROYALS]: MlbTeamKey.KANSAS_CITY_ROYALS,
  [MlbTeamFullName.LOS_ANGELES_ANGELS]: MlbTeamKey.LOS_ANGELES_ANGELS,
  [MlbTeamFullName.LOS_ANGELES_DODGERS]: MlbTeamKey.LOS_ANGELES_DODGERS,
  [MlbTeamFullName.MIAMI_MARLINS]: MlbTeamKey.MIAMI_MARLINS,
  [MlbTeamFullName.MILWAUKEE_BREWERS]: MlbTeamKey.MILWAUKEE_BREWERS,
  [MlbTeamFullName.MINNESOTA_TWINS]: MlbTeamKey.MINNESOTA_TWINS,
  [MlbTeamFullName.NEW_YORK_METS]: MlbTeamKey.NEW_YORK_METS,
  [MlbTeamFullName.NEW_YORK_YANKEES]: MlbTeamKey.NEW_YORK_YANKEES,
  [MlbTeamFullName.OAKLAND_ATHLETICS]: MlbTeamKey.OAKLAND_ATHLETICS,
  [MlbTeamFullName.PHILADELPHIA_PHILLIES]: MlbTeamKey.PHILADELPHIA_PHILLIES,
  [MlbTeamFullName.PITTSBURGH_PIRATES]: MlbTeamKey.PITTSBURGH_PIRATES,
  [MlbTeamFullName.SAN_DIEGO_PADRES]: MlbTeamKey.SAN_DIEGO_PADRES,
  [MlbTeamFullName.SAN_FRANCISCO_GIANTS]: MlbTeamKey.SAN_FRANCISCO_GIANTS,
  [MlbTeamFullName.SEATTLE_MARINERS]: MlbTeamKey.SEATTLE_MARINERS,
  [MlbTeamFullName.ST_LOUIS_CARDINALS]: MlbTeamKey.ST_LOUIS_CARDINALS,
  [MlbTeamFullName.TAMPA_BAY_RAYS]: MlbTeamKey.TAMPA_BAY_RAYS,
  [MlbTeamFullName.TEXAS_RANGERS]: MlbTeamKey.TEXAS_RANGERS,
  [MlbTeamFullName.TORONTO_BLUE_JAYS]: MlbTeamKey.TORONTO_BLUE_JAYS,
  [MlbTeamFullName.WASHINGTON_NATIONALS]: MlbTeamKey.WASHINGTON_NATIONALS,
  [MlbHistoricalTeamFullName.ATHLETICS]: MlbTeamKey.ATHLETICS,
  [MlbHistoricalTeamFullName.CALIFORNIA_ANGELS]: MlbTeamKey.CALIFORNIA_ANGELS,
  [MlbHistoricalTeamFullName.ANAHEIM_ANGELS]: MlbTeamKey.ANAHEIM_ANGELS,
  [MlbHistoricalTeamFullName.LOS_ANGELES_ANGELS_OF_ANAHEIM]: MlbTeamKey.LOS_ANGELES_ANGELS_OF_ANAHEIM,
  [MlbHistoricalTeamFullName.CLEVELAND_INDIANS]: MlbTeamKey.CLEVELAND_INDIANS,
  [MlbHistoricalTeamFullName.FLORIDA_MARLINS]: MlbTeamKey.FLORIDA_MARLINS,
  [MlbHistoricalTeamFullName.MONTREAL_EXPOS]: MlbTeamKey.MONTREAL_EXPOS,
  [MlbHistoricalTeamFullName.TAMPA_BAY_DEVIL_RAYS]: MlbTeamKey.TAMPA_BAY_DEVIL_RAYS,
};

export const NflAbbreviationToFullNameMap: { [key in NflTeam]: NflTeamFullName } = {
  [NflTeam.ARI]: NflTeamFullName.ARIZONA_CARDINALS,
  [NflTeam.ATL]: NflTeamFullName.ATLANTA_FALCONS,
  [NflTeam.BAL]: NflTeamFullName.BALTIMORE_RAVENS,
  [NflTeam.BUF]: NflTeamFullName.BUFFALO_BILLS,
  [NflTeam.CAR]: NflTeamFullName.CAROLINA_PANTHERS,
  [NflTeam.CHI]: NflTeamFullName.CHICAGO_BEARS,
  [NflTeam.CIN]: NflTeamFullName.CINCINNATI_BENGALS,
  [NflTeam.CLE]: NflTeamFullName.CLEVELAND_BROWNS,
  [NflTeam.DAL]: NflTeamFullName.DALLAS_COWBOYS,
  [NflTeam.DEN]: NflTeamFullName.DENVER_BRONCOS,
  [NflTeam.DET]: NflTeamFullName.DETROIT_LIONS,
  [NflTeam.GB]: NflTeamFullName.GREEN_BAY_PACKERS,
  [NflTeam.HOU]: NflTeamFullName.HOUSTON_TEXANS,
  [NflTeam.IND]: NflTeamFullName.INDIANAPOLIS_COLTS,
  [NflTeam.JAX]: NflTeamFullName.JACKSONVILLE_JAGUARS,
  [NflTeam.KC]: NflTeamFullName.KANSAS_CITY_CHIEFS,
  [NflTeam.LA]: NflTeamFullName.LOS_ANGELES_CHARGERS,
  [NflTeam.MIA]: NflTeamFullName.MIAMI_DOLPHINS,
  [NflTeam.MIN]: NflTeamFullName.MINNESOTA_VIKINGS,
  [NflTeam.NE]: NflTeamFullName.NEW_ENGLAND_PATRIOTS,
  [NflTeam.NO]: NflTeamFullName.NEW_ORLEANS_SAINTS,
  [NflTeam.NYG]: NflTeamFullName.NEW_YORK_GIANTS,
  [NflTeam.NYJ]: NflTeamFullName.NEW_YORK_JETS,
  [NflTeam.PHI]: NflTeamFullName.PHILADELPHIA_EAGLES,
  [NflTeam.PIT]: NflTeamFullName.PITTSBURGH_STEELERS,
  [NflTeam.SEA]: NflTeamFullName.SEATTLE_SEAHAWKS,
  [NflTeam.SF]: NflTeamFullName.SAN_FRANCISCO_49ERS,
  [NflTeam.TB]: NflTeamFullName.TAMPA_BAY_BUCCANEERS,
  [NflTeam.TEN]: NflTeamFullName.TENNESSEE_TITANS,
  [NflTeam.WAS]: NflTeamFullName.WASHINGTON_COMMANDERS,
};

export const TeamAbbreviationToFullNameMap: { [key in TeamType]: string } = {
  ...MlbAbbreviationToFullNameMap,
  ...NflAbbreviationToFullNameMap,
  ...MlbTeamKeyToFullNameMap,
};
